id: I99CFC90D
ocr_import_info:
  timestamp: '2023-09-28T04:49:42.933278+00:00'
  batch_id: batch-52f8
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 13:25:39.167522+00:00
last_modified: 2023-09-28 13:25:39.167531+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ74541
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ74541
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚད་མ་རྣམ་ངེས་ཀྱི་རྣམ་བཤད་ཐེག་གསུམ་ལམ་དུ་བགྲོད་པ་རྒྱལ་བའི་དགོངས་པ་རབ་གསལ།
  languages:
  - bo
  author: རྒྱལ་ཚབ་དར་མ་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.9636433255239772
  ocr_word_median_confidence_index: 0.9988693
bases:
  I4CZ74543:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ74543
      total_pages: 684
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ74543.txt
    statistics:
      ocr_word_median_confidence_index: 0.9988693
      ocr_word_mean_confidence_index: 0.9636433255239772
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
